title: Zhenhua Liu
position: Ph.D. Student
affiliation: Soochow University
email: zhliu0106 (at) gmail.com

plugins:
  - jekyll-spaceship
  - jekyll-last-modified-at
  # - jekyll-analytics

keywords: minimal academic
description: PhD student @ Soochow University
# canonical: https://cv.hqzhou.com

semantic_scholar: https://www.semanticscholar.org/author/Zhenhua-Liu/2294376388
google_scholar: https://scholar.google.com/citations?user=Toeubt0AAAAJ
# cv_link: ./assets/files/cv.pdf
github_link: https://github.com/zhliu0106
arxiv_link: https://zhliu0106.github.io/arxiv
affiliation_link: https://www.suda.edu.cn

avatar: ./assets/img/my_avatar.png
# favicon: ./assets/img/favicon.svg
favicon_svg: ./assets/img/favicon-3.min.svg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# jekyll_analytics:
#   GoogleAnalytics:
#     id: UA-284490532-1

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
